//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGenerator.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TProfile
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public int YearOfExp { get; set; }
        public string Gender { get; set; }
        public string Degree { get; set; }
        public string Occupation { get; set; }
        public string Address { get; set; }
        public string Nationality { get; set; }
        public string PhoneNo { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string AboutMe { get; set; }
        public string Photo { get; set; }
        public Nullable<int> IdUser { get; set; }
        public System.Guid IdProfile { get; set; }
    }
}
