//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGenerator.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TReference
    {
        public int Id { get; set; }
        public string Initial { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Relationship { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public int IdProfile { get; set; }
    }
}
