//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CVGenerator.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TResume
    {
        public int Id { get; set; }
        public int IdProfile { get; set; }
        public int IdTemplate { get; set; }
        public string Url { get; set; }
    }
}
