CREATE TABLE [dbo].[TUser]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] VARCHAR(254) NOT NULL, 
    [Password] VARCHAR(32) NOT NULL, 
    [Email] NVARCHAR(254) NOT NULL, 
    [Role] INT NOT NULL
)
